# Generated by Django 3.2.15 on 2022-10-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20221003_1517'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='inventory',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
