# Generated by Django 3.2.15 on 2022-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.TextField(blank=True, default=[], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(default='default_pic.ico', upload_to='profiles/'),
        ),
    ]
