# Generated by Django 3.2.15 on 2022-10-03 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcover', models.ImageField(blank=True, null=True, upload_to='bookcovers/')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
