# Generated by Django 3.2.15 on 2022-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20221003_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='default_book.ico', null=True, upload_to='bookcovers/'),
        ),
    ]
