# Generated by Django 3.2.15 on 2022-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.TextField(default='<function uuid4 at 0x000001F931143100>', unique=True),
        ),
    ]
