# Generated by Django 3.2.15 on 2022-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
