# Generated by Django 3.2.15 on 2022-11-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
