# Generated by Django 3.2.15 on 2022-11-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20221120_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='bookcovers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='mp3_files/'),
        ),
    ]
