# Generated by Django 3.2.15 on 2022-11-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='default_book.png', null=True, upload_to='bookcovers/'),
        ),
    ]
