# Generated by Django 3.2.15 on 2022-11-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
