# Generated by Django 3.2.15 on 2022-11-24 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20221121_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='mp3_file',
            field=models.FileField(blank=True, default='mp3_files/<django.db.models.fields.CharField>.mp3', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='mp3_files/')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
